const body = document.querySelector("body")
const night_day = document.querySelector(".night_day")
const span = document.querySelector(".mode")
const day = document.querySelector(".nav_right")
const day1 = document.querySelector(".hero_left")
const day2 = document.querySelector(".main_cards")
const day3 = document.querySelector(".main_left")
const day4 = document.querySelector(".icons")
night_day.addEventListener("click",()=>{
    span.classList.toggle("active")
    body.classList.toggle("active")
day.classList.toggle("active")
day1.classList.toggle("active")
day3.classList.toggle("active")
day2.classList.toggle("active")
day4.classList.toggle("active")
})